name: deardiary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_auth: ^4.15.1
  firebase_core: ^2.24.1
  intl: ^0.17.0
  firebase_database: ^10.3.8
  provider: ^6.1.1
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/



